// icd0006-2020s/React/homework/src/containers/statuses/Index.tsx
import { useEffect, useState, useContext } from "react";
import { Link } from "react-router-dom";
import Loader from "../../components/Loader";
import { IStatus } from "../../dto/IStatus";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { AppContext } from "../../context/AppContext";



const RowDisplay = (props: { status: IStatus }) => (
    <tr>
        <td>
            {props.status.name}
        </td>
        <td className="float-right">
            <Link to={'/statuses/' + props.status.id}>Details</Link>
            {useContext(AppContext).jwt === null ?
                <></>
                :
                <>
                    <span> | </span>
                    <Link to={'/statuses/edit/' + props.status.id}>Edit</Link>
                </>
            }
        </td>
    </tr>
);

const Index = () => {
    const [Statuses, setStatuses] = useState([] as IStatus[]);

    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });

    const loadData = async () => {
        let result = await BaseService.getAll<IStatus>('/statuses');

        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setStatuses(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []);

    return (
        <>
            <h1>Statuses</h1>
            <Link to={'/statuses/create'}>Create new status</Link>
            <table className="table">
                <thead>
                    <tr>
                        <th>
                            Status
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {Statuses.map(status =>
                        <RowDisplay status={status} key={status.id} />)
                    }
                </tbody>
            </table>
            <Loader {...pageStatus} />
        </>
    );
}

export { Index };

// icd0006-2020s/Vue/crud/src/views/Statuses/Index.vue
<template>
    <h1>Statuses</h1>
    <router-link
        :to="{
            name: 'StatusesCreate',
        }"
        >Create new</router-link
    >
    <br /><br />
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="status in statuses" v-bind:key="status.id">
                <td>
                    {{ status.name }}
                </td>
                <td class="float-right">
                    <router-link
                        :to="{
                            name: 'StatusesEdit',
                            params: { id: status.id },
                        }"
                        >Edit</router-link
                    >
                    |
                    <router-link
                        :to="{
                            name: 'StatusesDetails',
                            params: { id: status.id },
                        }"
                        >Details</router-link
                    >
                </td>
            </tr>
        </tbody>
    </table>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IStatus } from "@/domain/IStatus";
import { BaseService } from "@/services/BaseService";
import { ApiUrls } from "@/services/ApiUrls";

@Options({
    components: {},
    props: {},
})
export default class Index extends Vue {
    statuses: IStatus[] = [];
    mounted(): void {
        const statusService: BaseService<IStatus> = new BaseService(
            ApiUrls.apiBaseUrl + "Statuses/"
        );
        statusService.getAll().then((data) => {
            if (data.data != null) {
                this.statuses = data.data;
            }
        });
    }
}
</script>
