// icd0006-2020s/React/homework/src/containers/titles/Create.tsx
import { useState, useContext } from "react";
import { Redirect } from "react-router";
import { Link } from "react-router-dom";
import { ITitle } from "../../dto/ITitle";
import { BaseService } from "../../services/base-service";
import { AppContext } from "../../context/AppContext";
import Alert, { EAlertClass } from "../../components/Alert";

const initialTitleValues: ITitle = {
    id: '',
    name: '',
    nameId: ''
};

const Create = () => {
    const appState = useContext(AppContext);
    const [titleData, setTitleData] = useState(initialTitleValues);
    const [pass, setPass] = useState(false);
    const [alertMessage, setAlertMessage] = useState('');


    const UpdateClicked = async (e: Event) => {
        e.preventDefault();
        if (titleData.name === '') {
            setAlertMessage('Empty name!');
        };
        setAlertMessage('');
        let response = await BaseService.create<ITitle>('/titles', { name: titleData.name }, appState.jwt!);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage('');
            setPass(true);
        }
    }

    return (
        <>
            { pass ? <Redirect to="/titles" /> : null}
            <h1>Create</h1>
            <form onSubmit={(e) => e.preventDefault()}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />

                            <div className="form-group">
                                <label htmlFor="inputTitleName">Title</label>
                                <input
                                    className="form-control"
                                    type="text"
                                    id="inputTitleName"
                                    name="inputTitleName"
                                    value={titleData.name} onChange={(e) => setTitleData({ ...titleData, name: e.target.value })}
                                />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => UpdateClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Create</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
            <Link to={'/titles'}>Back to list</Link>
        </>
    );
}

export { Create }

// icd0006-2020s/Vue/crud/src/views/Titles/Create.vue
<template>
    <h1>Edit Title</h1>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-4">
            <form>
                <div class="form-group">
                    <label for="Input_Title">Title</label>
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Title"
                        name="Input_Title"
                        v-model.lazy="title.name"
                    />
                    <span class="text-danger field-validation-valid"></span>
                </div>

                <button
                    type="submit"
                    v-on:click.prevent="createClick"
                    class="btn btn-primary"
                >
                    Create
                </button>
            </form>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
    <router-link
        :to="{
            name: 'TitlesIndex',
        }"
        >Back to list</router-link
    >
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { ITitle } from "@/domain/ITitle";
import { BaseService } from "@/services/BaseService";
import { ApiUrls } from "@/services/ApiUrls";

@Options({
    components: {},
    props: {},
})
export default class Create extends Vue {
    title: ITitle = { id: "", name: "" };
    titleService!: BaseService<ITitle>;
    id!: string;
    mounted(): void {
        this.titleService = new BaseService(ApiUrls.apiBaseUrl + "Titles");
    }

    async createClick(): Promise<void> {
        const dto = {
            name: this.title.name,
        };
        this.titleService.create(dto).finally(() => {
            this.$router.push({ name: "TitlesIndex" });
        });
    }
}
</script>
