// icd0006-2020s/React/homework/src/containers/requirements/Create.tsx
import { useState, useContext } from "react";
import { Redirect } from "react-router";
import { Link } from "react-router-dom";
import { IRequirement } from "../../dto/IRequirement";
import { BaseService } from "../../services/base-service";
import { AppContext } from "../../context/AppContext";
import Alert, { EAlertClass } from "../../components/Alert";

const initialRequirementValues: IRequirement = {
    id: '',
    name: '',
    nameId: '',
    description: '',
    descriptionId: '',
    amount: null,
    price: 0,
};

const Create = () => {
    const appState = useContext(AppContext);
    const [requirementData, setRequirementData] = useState(initialRequirementValues);
    const [pass, setPass] = useState(false);
    const [alertMessage, setAlertMessage] = useState('');


    const UpdateClicked = async (e: Event) => {
        console.log("Clocked1");
        e.preventDefault();
        if (requirementData.name === '' || requirementData.description === '' || requirementData.price === null) {
            setAlertMessage('Empty value!');
        } else {
            setAlertMessage('');
            let response = await BaseService.create<IRequirement>('/requirements', { name: requirementData.name, description: requirementData.description, amount: requirementData.amount, price: requirementData.price }, appState.jwt!);
            console.log(response);
            if (!response.ok) {
                setAlertMessage(response.messages![0]);
            } else {
                setAlertMessage('');
                setPass(true);
            }
        }
    }


    return (
        <>
            { pass ? <Redirect to="/requirements" /> : null}
            <h1>Create</h1>
            <form onSubmit={(e) => e.preventDefault()}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />

                            <div className="form-group">
                                <label htmlFor="inputName">Name</label>
                                <input
                                    className="form-control"
                                    type="text"
                                    id="inputName"
                                    name="inputName"
                                    value={requirementData.name} onChange={(e) => setRequirementData({ ...requirementData, name: e.target.value })}
                                />
                            </div>
                            <div className="form-group">
                                <label htmlFor="inputDescription">Description</label>
                                <input
                                    className="form-control"
                                    type="text"
                                    id="inputDescription"
                                    name="inputDescription"
                                    value={requirementData.description} onChange={(e) => setRequirementData({ ...requirementData, description: e.target.value })}
                                />
                            </div>
                            <div className="form-group">
                                <label htmlFor="inputPrice">Price</label>
                                <input
                                    className="form-control"
                                    type="number"
                                    id="inputPrice"
                                    name="inputPrice"
                                    value={requirementData.price} onChange={(e) => setRequirementData({ ...requirementData, price: Number(e.target.value) })}
                                />
                            </div>
                            {requirementData.amount !== null ?
                                <div className="form-group">
                                    <label htmlFor="inputAmount">Amount</label>
                                    <input
                                        className="form-control"
                                        type="number"
                                        id="inputAmount"
                                        name="inputAmount"
                                        value={requirementData.amount!} onChange={(e) => setRequirementData({ ...requirementData, amount: Number(e.target.value) })}
                                    />
                                </div>
                                :
                                <></>
                            }
                            <div className="form-group">
                                <button onClick={(e) => UpdateClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Create</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
            <Link to={'/requirements'}>Back to list</Link>
        </>
    );

}

export { Create };

// icd0006-2020s/Vue/crud/src/views/Requirements/Create.vue
<template>
    <h1>Edit Requirement</h1>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-4">
            <form>
                <div class="form-group">
                    <label for="Input_Requirement_Name">Name</label>
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Name"
                        name="Input_Requirement_Name"
                        v-model.lazy="requirement.name"
                    />
                    <label for="Input_Requirement_Description"
                        >Description</label
                    >
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Description"
                        name="Input_Requirement_Description"
                        v-model.lazy="requirement.description"
                    />
                    <label for="Input_Requirement_Price">Price</label>
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Price"
                        name="Input_Requirement_Price"
                        v-model.lazy="requirement.price"
                    />
                </div>
                <button
                    type="submit"
                    v-on:click.prevent="createClick"
                    class="btn btn-primary"
                >
                    Create
                </button>
            </form>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
    <router-link
        :to="{
            name: 'RequirementsIndex',
        }"
        >Back to list</router-link
    >
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IRequirement } from "@/domain/IRequirement";
import { BaseService } from "@/services/BaseService";
import { ApiUrls } from "@/services/ApiUrls";

@Options({
    components: {},
    props: { id: String },
})
export default class Create extends Vue {
    requirement = {
        id: "",
        name: "",
        description: "",
        price: 0,
        amount: null,
    };

    requirementService!: BaseService<IRequirement>;

    id!: string;
    mounted(): void {
        this.requirementService = new BaseService(
            ApiUrls.apiBaseUrl + "Requirements"
        );
    }

    async createClick(): Promise<void> {
        const dto = {
            name: this.requirement.name,
            description: this.requirement.description,
            price: this.requirement.price,
            amount: this.requirement.amount,
        };
        this.requirementService.create(dto).finally(() => {
            this.$router.push({ name: "RequirementsIndex" });
        });
    }
}
</script>
