// icd0006-2020s/React/homework/src/containers/requirements/Edit.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { useEffect, useState, useContext } from "react";
import { Redirect } from "react-router";
import { Link } from "react-router-dom";
import { IRequirement } from "../../dto/IRequirement";
import Loader from "../../components/Loader";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { AppContext } from "../../context/AppContext";
import Alert, { EAlertClass } from "../../components/Alert";

const initialRequirementValues: IRequirement = {
    id: '',
    name: '',
    nameId: '',
    description: '',
    descriptionId: '',
    amount: 0,
    price: 0,
};

const Edit = () => {
    const appState = useContext(AppContext);
    const { id } = useParams() as IRouteId;
    const [requirementData, setRequirementData] = useState(initialRequirementValues);
    const [pass, setPass] = useState(false);
    const [alertMessage, setAlertMessage] = useState('');
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });

    const loadData = async () => {
        let result = await BaseService.get<IRequirement>('/requirements', id, appState.jwt!);

        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setRequirementData(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData();// eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const UpdateClicked = async (e: Event) => {
        e.preventDefault();
        if (requirementData.name === '' || requirementData.description === '' || requirementData.price === null) {
            setAlertMessage('Empty value!');
        };
        setAlertMessage('');
        let response = await BaseService.update<IRequirement>('/requirements', id, requirementData, appState.jwt!);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage('');
            setPass(true);
        }
    }

    const DeleteClicked = async (e: Event) => {
        e.preventDefault();
        setAlertMessage('');
        let response = await BaseService.delete<IRequirement>('/requirements', id, appState.jwt!);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage('');
            setPass(true);
        }

    }

    return (
        <>
            { pass ? <Redirect to="/requirements" /> : null}
            <h1>Edit</h1>
            <form onSubmit={(e) => e.preventDefault()}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <Loader {...pageStatus} />
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="inputName">Name</label>
                                <input
                                    className="form-control"
                                    type="text"
                                    id="inputName"
                                    name="inputName"
                                    value={requirementData.name} onChange={(e) => setRequirementData({ ...requirementData, name: e.target.value })}
                                />
                            </div>
                            <div className="form-group">
                                <label htmlFor="inputDescription">Description</label>
                                <input
                                    className="form-control"
                                    type="text"
                                    id="inputDescription"
                                    name="inputDescription"
                                    value={requirementData.description} onChange={(e) => setRequirementData({ ...requirementData, description: e.target.value })}
                                />
                            </div>
                            <div className="form-group">
                                <label htmlFor="inputPrice">Price</label>
                                <input
                                    className="form-control"
                                    type="number"
                                    id="inputPrice"
                                    name="inputPrice"
                                    value={requirementData.price} onChange={(e) => setRequirementData({ ...requirementData, price: Number(e.target.value) })}
                                />
                            </div>
                            {requirementData.amount !== null ?
                                <div className="form-group">
                                    <label htmlFor="inputAmount">Amount</label>
                                    <input
                                        className="form-control"
                                        type="number"
                                        id="inputAmount"
                                        name="inputAmount"
                                        value={requirementData.amount!} onChange={(e) => setRequirementData({ ...requirementData, amount: Number(e.target.value) })}
                                    />
                                </div>
                                :
                                <></>
                            }
                            <div className="form-group">
                                <button onClick={(e) => UpdateClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Update</button>
                                <button onClick={(e) => DeleteClicked(e.nativeEvent)} type="submit" className="btn btn-danger float-right">Delete</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
            <Link to={'/Names'}>Back to list</Link>
        </>
    );
}

export { Edit }

// icd0006-2020s/Vue/crud/src/views/Requirements/Edit.vue
<template>
    <h1>Edit Requirement</h1>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-4">
            <form>
                <div class="form-group">
                    <label for="Input_Requirement_Name">Name</label>
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Name"
                        name="Input_Requirement_Name"
                        v-model.lazy="requirement.name"
                    />
                    <label for="Input_Requirement_Description"
                        >Description</label
                    >
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Description"
                        name="Input_Requirement_Description"
                        v-model.lazy="requirement.description"
                    />
                    <label for="Input_Requirement_Price">Price</label>
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Price"
                        name="Input_Requirement_Price"
                        v-model.lazy="requirement.price"
                    />
                    <label
                        for="Input_Requirement_Amount"
                        v-if="requirement.amount !== null"
                        >Amount</label
                    >
                    <input
                        class="form-control"
                        type="text"
                        id="Input_Requirement_Amount"
                        name="Input_Requirement_Amount"
                        v-if="requirement.amount !== null"
                        v-model.number="requirement.amount"
                    />
                </div>

                <button
                    type="submit"
                    v-on:click.prevent="updateClick"
                    class="btn btn-primary"
                >
                    Update
                </button>
                <button
                    type="submit"
                    v-on:click.prevent="deleteClick"
                    class="btn btn-danger float-right"
                >
                    Delete
                </button>
            </form>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
    <router-link
        :to="{
            name: 'RequirementsIndex',
            params: { id: requirement.id },
        }"
        >Back to list</router-link
    >
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IRequirement } from "@/domain/IRequirement";
import { BaseService } from "@/services/BaseService";
import { ApiUrls } from "@/services/ApiUrls";

@Options({
    components: {},
    props: { id: String },
})
export default class Edit extends Vue {
    requirement: IRequirement = {
        id: "",
        name: "",
        description: "",
        price: 0,
        amount: -1,
    };

    requirementService!: BaseService<IRequirement>;

    id!: string;
    mounted(): void {
        this.requirementService = new BaseService(
            ApiUrls.apiBaseUrl + "Requirements"
        );
        this.requirementService.get(this.id).then((data) => {
            if (data.data != null) {
                this.requirement = data.data;
            }
        });
    }

    async updateClick(): Promise<void> {
        const dto: IRequirement = {
            id: this.requirement.id,
            name: this.requirement.name,
            description: this.requirement.description,
            price: this.requirement.price,
            amount: this.requirement.amount,
        };
        this.requirementService.update(this.id, dto).finally(() => {
            this.$router.push({ name: "RequirementsIndex" });
        });
    }

    async deleteClick(): Promise<void> {
        this.requirementService.delete(this.id).finally(() => {
            this.$router.push({ name: "RequirementsIndex" });
        });
    }
}
</script>
