// icd0006-2020s/Vue/crud/src/views/Statuses/Details.vue
<template>
    <h1>Details</h1>

    <div>
        <h4>Status</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">Id</dt>
            <dd class="col-sm-8">
                {{ id }}
            </dd>
            <dt class="col-sm-4">Name</dt>
            <dd class="col-sm-8">
                {{ status.name }}
            </dd>
        </dl>
    </div>
    <div>
        <router-link
            :to="{
                name: 'StatusesIndex',
            }"
            aria-haspopup="true"
            aria-expanded="false"
            >Back to list</router-link
        >
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IStatus } from "@/domain/IStatus";
import { BaseService } from "@/services/BaseService";
import { ApiUrls } from "@/services/ApiUrls";

@Options({
    components: {},
    props: {
        id: String,
    },
})
export default class Details extends Vue {
    status: IStatus = { id: "", name: "" };
    id!: string;
    mounted(): void {
        const statusService: BaseService<IStatus> = new BaseService(
            ApiUrls.apiBaseUrl + "Statuses"
        );
        statusService.get(this.id).then((data) => {
            if (data.data != null) {
                this.status = data.data;
            }
        });
    }
}
</script>

// icd0006-2020s/React/homework/src/containers/statuses/Details.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { useEffect, useState, useContext } from "react";
import { Link } from "react-router-dom";
import { IStatus } from "../../dto/IStatus";
import Loader from "../../components/Loader";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { AppContext } from "../../context/AppContext";

const initialStatusValues: IStatus = {
    id: '',
    name: '',
    nameId: ''
};

const Details = () => {
    const appState = useContext(AppContext);
    const { id } = useParams() as IRouteId;
    const [status, setStatus] = useState(initialStatusValues);


    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });

    const loadData = async () => {
        let result = await BaseService.get<IStatus>('/statuses', id, appState.jwt!);

        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setStatus(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData(); // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return (
        <>
            <h1>Details</h1>
            <div>
                <h4>Status</h4>
                <hr />
                <Loader {...pageStatus} />

                <dl className="row">
                    <dt className="col-sm-4">Id</dt>
                    <dd className="col-sm-8">
                        {status.id}
                    </dd>

                    <dt className="col-sm-4">Name</dt>
                    <dd className="col-sm-8">
                        {status.name}
                    </dd>
                </dl>
            </div>
            <div>
                <Link
                    to="/statuses"
                >Back to list</Link>
            </div >
        </>
    );
}

export { Details };
