// icd0006-2020s/Autokool/src/containers/identity/Login.tsx
import React, { useContext, useState } from "react";
import { Redirect } from "react-router";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";



const Login = () => {
    const appState = useContext(AppContext);
    const resource = appState.langResources.frontEnd.containers.identity.login;

    const [loginData, setLoginData] = useState({ userName: '', password: '' });
    const [alertMessage, setAlertMessage] = useState('');

    const logInClicked = async (e: Event) => {
        e.preventDefault();
        if (loginData.userName === '' || loginData.password === '') {
            setAlertMessage(resource.emptyInputs);
        };
        setAlertMessage('');
        let response = await IdentityService.Login(loginData, appState.currentLanguage.name);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage('');
            appState.jwt = response.data!.token;
            appState.userName = response.data!.userName;
            appState.firstName = response.data!.firstname;
            appState.lastName = response.data!.lastname;
            appState.title = null;
            appState.contractId = null;
            appState.setAuthInfo(appState.jwt, appState.userName, appState.firstName, appState.lastName, appState.title, appState.contractId, appState.supportedLanguages, appState.currentLanguage, appState.langResources);
        }
    }

    return (
        <>
            { appState.jwt !== null ? <Redirect to="/" /> : null}
            <form onSubmit={(e) => logInClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_username">{resource.username}</label>
                                <input value={loginData.userName} onChange={e => setLoginData({ ...loginData, userName: e.target.value })} className="form-control" type="text" id="Input_Username" name="Input.Username" placeholder="" autoComplete="username" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Password">{resource.password}</label>
                                <input value={loginData.password} onChange={e => setLoginData({ ...loginData, password: e.target.value })} className="form-control" type="password" id="Input_Password" name="Input.Password" placeholder="" autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => logInClicked(e.nativeEvent)} type="submit" className="btn btn-primary">{resource.logIn}</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default Login;

// icd0006-2020s/Vue/crud/src/views/identity/Login.vue
<template>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-6">
            <h4>Use a local account to log in.</h4>
            <hr />
            <div class="form-group">
                <label for="Input_Username">Username</label>
                <input
                    class="form-control"
                    type="text"
                    id="Input_Username"
                    v-model="username"
                />
            </div>
            <div class="form-group">
                <label for="Input_Password">Password</label>
                <input
                    class="form-control"
                    type="password"
                    id="Input_Password"
                    v-model="password"
                />
            </div>
            <div class="form-group">
                <button
                    @click="loginClicked($event)"
                    type="submit"
                    class="btn btn-primary"
                >
                    Log in
                </button>
            </div>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store";

@Options({
    components: {},
    props: {},
})
export default class Login extends Vue {
    username: string = "admin";
    password: string = "DucksG0Quack!";

    async loginClicked(): Promise<void> {
        const passed: boolean = await store.dispatch("logIn", {
            username: this.username,
            password: this.password,
        });
        if (passed) {
            this.$router.push("/");
        }
    }
}
</script>
